import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { defineConfig, type Plugin } from 'vite';

/**
 * Build-time curriculum fix.
 *
 * The curriculum data contains Primary and JHS strands in the same subject
 * object. FormInput historically selected the first matching strand without
 * considering the selected class level, which could make Basic 7-9 show a
 * Basic 1-6 Content Standard. This transform keeps the existing FormInput
 * UI/features intact while making the curriculum cascade level-aware.
 */
function curriculumLevelFix(): Plugin {
  return {
    name: 'curriculum-level-fix',
    enforce: 'pre',
    transform(code, id) {
      if (!id.endsWith('/src/components/FormInput.tsx')) return null;

      const start = code.indexOf('  // Available subjects and cascading curriculum data from database');
      const end = code.indexOf('  const handleResetToSubjectPresets = () => {');
      if (start === -1 || end === -1 || end <= start) return null;

      const replacement = String.raw`  // Level-aware curriculum helpers.
  const normalize = (value: string) => (value || '').toLowerCase().trim();

  const getStrandsForLevel = (subjectData: any, classLevel: string) => {
    if (!subjectData) return [];
    const prefix = getLevelPrefix(classLevel);
    const strands = subjectData.strands || [];

    // JHS strands generated by the curriculum pipeline carry an explicit
    // levels array (e.g. ['Basic 7']) and a _jhs id marker.
    if (['B7', 'B8', 'B9'].includes(prefix)) {
      const target = prefix === 'B7' ? 'Basic 7' : prefix === 'B8' ? 'Basic 8' : 'Basic 9';
      const jhs = strands.filter((s: any) => {
        const levels = Array.isArray(s.levels) ? s.levels.map((v: any) => String(v).toLowerCase()) : [];
        const id = String(s.id || '').toLowerCase();
        return levels.includes(target.toLowerCase()) || id.includes('_jhs');
      });
      return jhs;
    }

    // Primary strands are the non-JHS strands. For Basic 1-6, their content
    // standards are filtered below by the exact B1-B6 code prefix.
    return strands.filter((s: any) => !String(s.id || '').toLowerCase().includes('_jhs'));
  };

  const getLevelContentStandards = (subStrand: any, classLevel: string) => {
    if (!subStrand) return [];
    const all = subStrand.contentStandards || [];
    const prefix = getLevelPrefix(classLevel);
    const basicPrefix = /^B[1-9]\./i.test(String(all[0]?.code || '')) ||
      all.some((cs: any) => /^B[1-9]\./i.test(String(cs?.code || '')));

    if (basicPrefix && /^B[1-9]$/.test(prefix)) {
      const matching = all.filter((cs: any) => String(cs?.code || '').toUpperCase().startsWith(prefix + '.'));
      if (matching.length) return matching;
    }

    // KG/Nursery datasets may use non-Bx codes, so preserve their standards.
    return all;
  };

  const getBestCSForLevel = (subStrand: any, classLevel: string) => {
    const standards = getLevelContentStandards(subStrand, classLevel);
    return standards[0];
  };

  const selectedSubjectData = GHANA_CURRICULUM_DATA.find(s =>
    normalize(s.name) === normalize(inputs.subject) ||
    normalize(inputs.subject).includes(normalize(s.name)) ||
    normalize(s.name).includes(normalize(inputs.subject))
  ) || GHANA_CURRICULUM_DATA[0];

  const availableStrands = getStrandsForLevel(selectedSubjectData, inputs.classLevel);

  const selectedStrandData = availableStrands.find((s: any) =>
    normalize(s.name) === normalize(inputs.strand) ||
    normalize(inputs.strand).includes(normalize(s.name)) ||
    normalize(s.name).includes(normalize(inputs.strand))
  ) || availableStrands[0];

  const availableSubStrands = selectedStrandData ? selectedStrandData.subStrands : [];

  const selectedSubStrandData = availableSubStrands.find((ss: any) =>
    normalize(ss.name) === normalize(inputs.subStrand) ||
    normalize(inputs.subStrand).includes(normalize(ss.name)) ||
    normalize(ss.name).includes(normalize(inputs.subStrand))
  ) || availableSubStrands[0];

  const availableContentStandards = getLevelContentStandards(selectedSubStrandData, inputs.classLevel);

  const selectedCSData = availableContentStandards.find((cs: any) =>
    normalize(inputs.contentStandard).startsWith(normalize(cs.code)) ||
    normalize(cs.code) === normalize(inputs.contentStandard) ||
    normalize(inputs.contentStandard).includes(normalize(cs.code))
  ) || getBestCSForLevel(selectedSubStrandData, inputs.classLevel) || availableContentStandards[0];

  const availableIndicators = selectedCSData ? selectedCSData.indicators : [];

  const selectedIndData = availableIndicators.find((ind: any) =>
    normalize(inputs.indicator).startsWith(normalize(ind.code)) ||
    normalize(ind.code) === normalize(inputs.indicator) ||
    normalize(inputs.indicator).includes(normalize(ind.code))
  ) || availableIndicators[0];

  // Auto update the entire curriculum cascade when the subject changes.
  const handleSubjectChange = (subjectName: string) => {
    const subjData = GHANA_CURRICULUM_DATA.find(s => normalize(s.name) === normalize(subjectName)) || GHANA_CURRICULUM_DATA[0];
    const levelStrands = getStrandsForLevel(subjData, inputs.classLevel);
    const firstStrand = levelStrands[0];
    const firstSubStrand = firstStrand?.subStrands?.[0];
    const bestCS = getBestCSForLevel(firstSubStrand, inputs.classLevel);
    const firstInd = bestCS?.indicators?.[0];

    const autoRef = getNaCCACurriculumReference(
      subjectName,
      inputs.classLevel,
      firstStrand ? firstStrand.name : '',
      firstSubStrand ? firstSubStrand.name : '',
      firstInd ? firstInd.code : ''
    );

    setInputs(prev => ({
      ...prev,
      subject: subjectName,
      strand: firstStrand ? firstStrand.name : '',
      subStrand: firstSubStrand ? firstSubStrand.name : '',
      contentStandard: bestCS ? \`\${bestCS.code}: \${bestCS.description}\` : '',
      indicator: firstInd ? \`\${firstInd.code}: \${firstInd.description}\` : '',
      references: autoRef
    }));
  };

  const handleStrandChange = (strandName: string) => {
    const strData = availableStrands.find((s: any) => s.name === strandName);
    const firstSubStrand = strData?.subStrands?.[0];
    const bestCS = getBestCSForLevel(firstSubStrand, inputs.classLevel);
    const firstInd = bestCS?.indicators?.[0];

    const autoRef = getNaCCACurriculumReference(
      inputs.subject,
      inputs.classLevel,
      strandName,
      firstSubStrand ? firstSubStrand.name : '',
      firstInd ? firstInd.code : ''
    );

    setInputs(prev => ({
      ...prev,
      strand: strandName,
      subStrand: firstSubStrand ? firstSubStrand.name : '',
      contentStandard: bestCS ? \`\${bestCS.code}: \${bestCS.description}\` : '',
      indicator: firstInd ? \`\${firstInd.code}: \${firstInd.description}\` : '',
      references: autoRef
    }));
  };

  const handleSubStrandChange = (subStrandName: string) => {
    const subStrData = availableSubStrands.find((ss: any) => ss.name === subStrandName);
    const bestCS = getBestCSForLevel(subStrData, inputs.classLevel);
    const firstInd = bestCS?.indicators?.[0];

    const autoRef = getNaCCACurriculumReference(
      inputs.subject,
      inputs.classLevel,
      inputs.strand,
      subStrandName,
      firstInd ? firstInd.code : ''
    );

    setInputs(prev => ({
      ...prev,
      subStrand: subStrandName,
      contentStandard: bestCS ? \`\${bestCS.code}: \${bestCS.description}\` : '',
      indicator: firstInd ? \`\${firstInd.code}: \${firstInd.description}\` : '',
      references: autoRef
    }));
  };

  const handleCSChange = (csCode: string) => {
    const csData = availableContentStandards.find((cs: any) =>
      normalize(cs.code) === normalize(csCode) ||
      normalize(csCode).startsWith(normalize(cs.code))
    );
    const firstInd = csData?.indicators?.[0];

    const autoRef = getNaCCACurriculumReference(
      inputs.subject,
      inputs.classLevel,
      inputs.strand,
      inputs.subStrand,
      firstInd ? firstInd.code : ''
    );

    setInputs(prev => ({
      ...prev,
      contentStandard: csData ? \`\${csData.code}: \${csData.description}\` : csCode,
      indicator: firstInd ? \`\${firstInd.code}: \${firstInd.description}\` : '',
      references: autoRef
    }));
  };

  const handleIndicatorChange = (indCode: string) => {
    let foundInd: any = null;
    let foundCS: any = null;

    // Search only the already level-filtered Content Standards.
    for (const cs of availableContentStandards) {
      for (const ind of cs.indicators || []) {
        if (normalize(ind.code) === normalize(indCode) || normalize(indCode).startsWith(normalize(ind.code))) {
          foundInd = ind;
          foundCS = cs;
          break;
        }
      }
      if (foundInd) break;
    }

    const indData = foundInd || availableIndicators.find((ind: any) => ind.code === indCode);
    const csData = foundCS || selectedCSData;

    const autoRef = getNaCCACurriculumReference(
      inputs.subject,
      inputs.classLevel,
      inputs.strand,
      inputs.subStrand,
      indData ? indData.code : indCode
    );

    setInputs(prev => ({
      ...prev,
      ...(csData ? { contentStandard: \`\${csData.code}: \${csData.description}\` } : {}),
      indicator: indData ? \`\${indData.code}: \${indData.description}\` : indCode,
      references: autoRef
    }));
  };

  // Changing class level must recalculate the whole curriculum cascade,
  // not merely swap the Content Standard inside the previous level's strand.
  const handleClassLevelChange = (newLevel: string) => {
    const subjData = GHANA_CURRICULUM_DATA.find(s => normalize(s.name) === normalize(inputs.subject)) || GHANA_CURRICULUM_DATA[0];
    const levelStrands = getStrandsForLevel(subjData, newLevel);
    const newStrand = levelStrands.find((s: any) => normalize(s.name) === normalize(inputs.strand)) || levelStrands[0];
    const subStrands = newStrand?.subStrands || [];
    const newSubStrand = subStrands.find((ss: any) => normalize(ss.name) === normalize(inputs.subStrand)) || subStrands[0];
    const bestCS = getBestCSForLevel(newSubStrand, newLevel);
    const firstInd = bestCS?.indicators?.[0];

    const autoRef = getNaCCACurriculumReference(
      inputs.subject,
      newLevel,
      newStrand ? newStrand.name : '',
      newSubStrand ? newSubStrand.name : '',
      firstInd ? firstInd.code : ''
    );

    setInputs(prev => ({
      ...prev,
      classLevel: newLevel,
      strand: newStrand ? newStrand.name : '',
      subStrand: newSubStrand ? newSubStrand.name : '',
      contentStandard: bestCS ? \`\${bestCS.code}: \${bestCS.description}\` : '',
      indicator: firstInd ? \`\${firstInd.code}: \${firstInd.description}\` : '',
      references: autoRef
    }));
  };

`;

      const transformed = code.slice(0, start) + replacement + code.slice(end);
      return { code: transformed, map: null };
    },
  };
}

export default defineConfig(() => {
  return {
    plugins: [curriculumLevelFix(), react(), tailwindcss()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      hmr: process.env.DISABLE_HMR !== 'true',
      watch: process.env.DISABLE_HMR === 'true' ? null : {},
    },
  };
});